# Generated by Django 3.2.3 on 2022-12-02 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cantidadPi',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='costoPi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
