# Generated by Django 3.2.3 on 2022-12-03 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0002_auto_20221201_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cantidadPi',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
