# Generated by Django 3.2.3 on 2022-12-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0003_alter_pizza_cantidadpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='saboresPi',
            field=models.CharField(default='20', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tamanoPi',
            field=models.CharField(default='20', max_length=20),
        ),
    ]
