# Generated by Django 3.2.3 on 2022-12-03 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pasteles', '0002_auto_20221201_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastel',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
