# Generated by Django 3.2.3 on 2022-12-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pasteles', '0003_alter_pastel_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastel',
            name='sabores',
            field=models.CharField(default='20', max_length=20),
        ),
        migrations.AlterField(
            model_name='pastel',
            name='tamano',
            field=models.CharField(default='20', max_length=20),
        ),
    ]
