# Generated by Django 3.2.3 on 2022-12-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pasteles', '0004_auto_20221202_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastel',
            name='sabores',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pastel',
            name='tamano',
            field=models.CharField(max_length=20),
        ),
    ]
